# Generated by Django 6.0.2 on 2026-02-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_about_created_at_about_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='aboute_heading',
            new_name='about_heading',
        ),
    ]
