# Generated by Django 6.0.2 on 2026-02-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Social Link'},
        ),
    ]
